# Generated by Django 4.2.23 on 2025-07-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='original_quantity_available',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
